services:
  traefik:
    extends:
      file: ./traefik/docker-compose.yaml
      service: traefik

  pihole:
    extends:
      file: ./pihole/docker-compose.yaml
      service: pihole

  nginx:
    extends:
      file: ./nginx/docker-compose.yaml
      service: nginx

  wgeasy:
    extends:
      file: ./wgeasy/docker-compose.yaml
      service: wg-easy
    
  copyparty:
    extends:
      file: ./copyparty/docker-compose.yaml
      service: copyparty
  
  laravel_app:
    extends:
      file: ./websters/docker-compose.yaml
      service: app

  laravel_nginx:
    extends:
      file: ./websters/docker-compose.yaml
      service: nginx

  laravel_mysql:
    extends:
      file: ./websters/docker-compose.yaml
      service: mysql

networks:
  traefik:
    external: true    
    name: traefik_network

volumes:
  etc_wireguard: {}   