services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "80:80/tcp"
      #- "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      #- "123:123/udp"
    environment:
      TZ: 'Europe/Vienna'
      FTLCONF_webserver_api_password: 'Stevan-20060901!'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    networks:
      - traefik
  labels:
    traefik.enable: "true"

    traefik.docker.network: "traefik_network"  # recommended

    # HTTPS router
    traefik.http.routers.pihole.rule: "Host(`pihole.stevan.sexidude.com`)"
    traefik.http.routers.pihole.entrypoints: "websecure"
    traefik.http.routers.pihole.tls: "true"
    traefik.http.routers.pihole.tls.certresolver: "ssl"

    # HTTP -> HTTPS redirect router
    traefik.http.routers.pihole-http.rule: "Host(`pihole.stevan.sexidude.com`)"
    traefik.http.routers.pihole-http.entrypoints: "web"
    traefik.http.routers.pihole-http.middlewares: "redirect-to-https"

    # Redirect middleware
    traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"
    
networks:
  traefik:
    external: true
    name: traefik_network  